[package]
name = "cc20"
version = "0.1.0"
authors = ["Murad <muradkarammaev@gmail.com>"]
edition = "2018"

[dependencies]
getopts = "0.2"
chacha20 = { version = "0.1", path = ".."}
rust-crypto = "^0.2"
rand_core = "0.5"
rand = "0.7"
